export const cardImages = {
  koiiCLI:
    require(`/img/cards/koii-cli.svg`)
    .default,
  koiiJSAPI:
    require(`/img/cards/koii-javascript-api.svg`)
    .default,
  philosophy:
    require(`/img/cards/philosophy.svg`)
    .default,
  tools:
    require(`/img/cards/tools.svg`)
    .default,
  finnie:
    require(`/img/cards/get-finnie-wallet.svg`)
    .default,
  koiinode:
  require(`/img/cards/run-koii-node.svg`)
  .default,
  discord:
  require(`/img/cards/discord.svg`)
  .default,
  community:
  require(`/img/cards/community.svg`)
  .default,
  twitter:
  require(`/img/cards/twitter.svg`)
  .default,
};
