export const cardImages = {
  createKoiiTask:
    require(`@site/develop/img/Create_a_koii_task.png`)
      .default,
  koiiCLI:
    require(`@site/develop/img/Koii_CLI.svg`)
    .default,
  koiiJSAPI:
    require(`@site/develop/img/Koii_JavaScript_API.svg`)
    .default,
  Philosophy:
    require(`@site/develop/img/Philosophy_1.svg`)
    .default,
  tools2:
    require(`@site/develop/img/Tools.svg`)
    .default,
  finnie:
    require(`@site/concepts/introduction/img/get_finnie_wallet.svg`)
    .default,
  koiinode:
  require(`@site/concepts/introduction/img/start_running_koii_node.svg`)
  .default,
  discord:
  require(`@site/faq/questions/img/discord.svg`)
  .default,
};
